context:
  version: 0.39.26

package:
  name: bicep
  version: ${{ version }}

source:
  - git: https://github.com/Azure/bicep
    tag: v${{ version }}
    target_directory: src
  - url: https://github.com/Azure/bicep/archive/refs/tags/v${{ version }}.tar.gz
    sha256: f74437071a4ce5982ee2e9f3fb2c1e8399db9d561e1884a5bfdca52118924307

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet =9
    - nuget-license <4
  run:
    - dotnet =9

tests:
  - script:
      - bicep --help

about:
  license: MIT
  license_file:
    - LICENSE
    - src/license-files_bicep/
    - src/license-files_bicep-langserver/
  summary: Bicep is a declarative language for describing and deploying Azure resources
  homepage: https://github.com/Azure/bicep
  repository: https://github.com/Azure/bicep

extra:
  recipe-maintainers:
    - danielnachun
